[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

#[build]
#target = "x86_64-unknown-uefi.json"
#rustflags = ["-C", "linker=arm-none-eabi-gcc"]

[build]
rustflags = ["-C", "link-arg=-nostdlib", "-C", "link-arg=-static", "-C", "relocation-model=pic", "-C", "link-arg=-Tshellcode.ld"]
target = "arm-unknown-linux-gnueabi"
#target = "shellcode.json"

[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"
