[package]
name = "n6g_dumper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libusb = "0.3"
libc = "0.2.151"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
log = "0.4.20"
