[package]
name = "scsi_writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
progression = "0.1.15"
sudo = "0.6.0"